openapi: 3.0.2
info:
  description: This API provides Supplies list
  version: 0.2.0
  title: Supplies List API
  contact:
    email: wuhan2020@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: contributors
    description: Secured write permission calls
  - name: developers
    description: Operations available to regular developers
paths:
  /supplies:
    get:
      tags:
        - developers
      summary: searches supplies
      operationId: searchSupplies
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplyItem'
        '400':
          description: bad input parameter
    post:
      tags:
        - contributors
      summary: adds a supply item
      operationId: addSupply
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplyItem'
        description: Supply item to add
servers:
  - url: 'https://virtserver.swaggerhub.com/wuhan2020/supplies/0.2.0'
components:
  schemas:
    SupplyItem:
      type: object
      required:
        - id
        - name
        - std
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: 医用口罩
        std:
          type: array
          items:
            $ref: '#/components/schemas/Standard'
        releaseDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    Standard:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: GB 19083-2010
        desc:
          type: string
          example: 国家标医用标准